Sync install from alx.sh

diff --git a/static/install b/static/install
--- a/static/install
+++ b/static/install
@@ -1,48 +1,60 @@
 #!/bin/sh
 # SPDX-License-Identifier: MIT
 
-set -e
+# Truncation guard
+if true; then
+    set -e
 
-export LC_ALL=en_US.UTF-8
-export LANG=en_US.UTF-8
-export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
+    export LC_ALL=en_US.UTF-8
+    export LANG=en_US.UTF-8
+    export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
 
-export VERSION_FLAG=https://cdn.asahilinux.org/installer/latest
-export INSTALLER_BASE=https://cdn.asahilinux.org/installer
-export INSTALLER_DATA=https://tobhe.de/ubuntu/installer_data.json
-export REPO_BASE=https://files.tobhe.de/ubuntu
+    export VERSION_FLAG=https://cdn.asahilinux.org/installer/latest
+    export INSTALLER_BASE=https://cdn.asahilinux.org/installer
+    export INSTALLER_DATA=https://tobhe.de/ubuntu/installer_data.json
+    export REPO_BASE=https://files.tobhe.de/ubuntu
 
-#TMP="$(mktemp -d)"
-TMP=/tmp/asahi-install
+    #TMP="$(mktemp -d)"
+    TMP=/tmp/asahi-install
 
-echo "Bootstrapping installer:"
+    echo "Bootstrapping installer:"
 
-mkdir -p "$TMP"
-cd "$TMP"
+    if [ -e "$TMP" ]; then
+        mv "$TMP" "$TMP-$(date +%Y%m%d-%H%M%S)"
+    fi
 
-echo "  Checking version..."
+    mkdir -p "$TMP"
+    cd "$TMP"
 
-PKG_VER="$(curl --no-progress-meter -L "$VERSION_FLAG")"
-echo "  Version: $PKG_VER"
+    echo "  Checking version..."
 
-PKG="installer-$PKG_VER.tar.gz"
+    PKG_VER="$(curl --no-progress-meter -L "$VERSION_FLAG")"
+    echo "  Version: $PKG_VER"
 
-echo "  Downloading..."
+    PKG="installer-$PKG_VER.tar.gz"
 
-curl --no-progress-meter -L -o "$PKG" "$INSTALLER_BASE/$PKG"
-curl --no-progress-meter -L -O "$INSTALLER_DATA"
+    echo "  Downloading..."
 
-echo "  Extracting..."
+    curl --no-progress-meter -L -o "$PKG" "$INSTALLER_BASE/$PKG"
+    if ! curl --no-progress-meter -L -O "$INSTALLER_DATA"; then
+        echo "    Error downloading installer_data.json. GitHub might be blocked in your network."
+        echo "    Please consider using a VPN if you experience issues."
+        echo "    Trying workaround..."
+        curl --no-progress-meter -L -O "$INSTALLER_DATA_ALT"
+    fi
 
-tar xf "$PKG"
+    echo "  Extracting..."
 
-echo "  Initializing..."
-echo
+    tar xf "$PKG"
 
-if [ "$USER" != "root" ]; then
-    echo "The installer needs to run as root."
-    echo "Please enter your sudo password if prompted."
-    exec caffeinate -dis sudo -E ./install.sh "$@"
-else
-    exec caffeinate -dis ./install.sh "$@"
+    echo "  Initializing..."
+    echo
+
+    if [ "$USER" != "root" ]; then
+        echo "The installer needs to run as root."
+        echo "Please enter your sudo password if prompted."
+        exec caffeinate -dis sudo -E ./install.sh "$@"
+    else
+        exec caffeinate -dis ./install.sh "$@"
+    fi
 fi
